### PR TITLE
Add a method to assert element visibility

### PR DESCRIPTION
**Pull request by pjcalvo**
This library has great potential, but it is currently small so I found myself all the time writing different forms of assertions. This PR is the first of a series that will try to add as much as validations to web elements.

I wanted to write this method first, cause it is really simple so I will appreciate your feedback.

Notes:
* Added a `toBeVisible` validation.
* Wrote unit tests.
* Added typings
* Modified README

Note: It will be nice to have documented all the methods that we might want to add..

@mmarkelov @mxschmitt

### CODE REVIEW

**Comment by mskelton** [comment]
@pjcalvo Out of curiosity, have you tried using `expect(page).waitForSelector('#foobar', { state: 'visible' })`?

**Comment by pjcalvo** [comment]
> @pjcalvo Out of curiosity, have you tried using `expect(page).waitForSelector('#foobar', { state: 'visible' })`?

Yes, that works just fine actually. I am not trying to find a work around, I will start adding more of these methods to make the library as simple and extensive as possible. 

`expect(page).waitForSelector('#foobar', { state: 'visible' })`
`expect(page).toBeDisplayed(#foobar)`

Both work fine. Users can decide what to use.

**Comment by mskelton** [comment]
@pjcalvo If it does the same thing as `.toHaveSelector(selector, { state: 'visible' })`, we should be able to make the matcher just pass it's args through to `toHaveSelector` so we don't have to have a completely new matcher with fairly duplicated code.

**Comment by pjcalvo** [comment]
That would make sense. I will look into updating the code. Thanks.

**Comment by mskelton** [comment]
`toHaveSelector` with `state: 'visible'` should accomplish the same goal you are aiming for with this PR as it performs the same actionability checks that `isVisible` does.

**Comment by pjcalvo** [comment]
> `toHaveSelector` with `state: 'visible'` should accomplish the same goal you are aiming for with this PR as it performs the same actionability checks that `isVisible` does.

Great. So I will work on another PR to update the Readme and allow other to know about this...

**Pull request closed without merging**
